// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechInfoLookUp.Data;

namespace TechInfoLookUp.Migrations
{
    [DbContext(typeof(TechInfoDbContext))]
    [Migration("20210219090927_CHANGE_TAG_AND_TECH_RELATIONSHIP_TO_ONE_TO_MANY")]
    partial class CHANGE_TAG_AND_TECH_RELATIONSHIP_TO_ONE_TO_MANY
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.Tech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("Techs");
                });

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.Tech", b =>
                {
                    b.HasOne("TechInfoLookUp.Data.Entities.Tag", "Tag")
                        .WithMany("Techs")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.Tag", b =>
                {
                    b.Navigation("Techs");
                });
#pragma warning restore 612, 618
        }
    }
}
