// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechInfoLookUp.Data;

namespace TechInfoLookUp.Migrations
{
    [DbContext(typeof(TechInfoDbContext))]
    [Migration("20210219050923_ADD_TECH_TECHTAG")]
    partial class ADD_TECH_TECHTAG
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.Tech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tech");
                });

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.TechTag", b =>
                {
                    b.Property<int>("TechId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("TechId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TechTag");
                });

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.TechTag", b =>
                {
                    b.HasOne("TechInfoLookUp.Data.Entities.Tag", "Tag")
                        .WithMany("TechTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechInfoLookUp.Data.Entities.Tech", "Tech")
                        .WithMany("TechTags")
                        .HasForeignKey("TechId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Tech");
                });

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.Tag", b =>
                {
                    b.Navigation("TechTags");
                });

            modelBuilder.Entity("TechInfoLookUp.Data.Entities.Tech", b =>
                {
                    b.Navigation("TechTags");
                });
#pragma warning restore 612, 618
        }
    }
}
