name: Deploy to Heroku

on:
  push:
    branches:
    - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'ittechinfo' }}

jobs:
  build:
    name: Replace connection string
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "HEROKU_POSTGRES_CONNECTION_STRING"
        replace: ${{ secrets.HEROKU_POSTGRES_CONNECTION_STRING }}
        include: "appsettings.json"

  build:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME